name: test
dependencies:
  - pandas>=1.1.3
  - seaborn
  - numpy
  - scipy
  - requests
  - rdkit=2020.09
  - scikit-learn
  - scipy
  - pytorch >=1.7.0,<2.0.0
  - cpuonly
  - pytest
  - pytest-cov
  - pymatgen>=2020.10.9
  - ruamel.yaml
  - tqdm
  - mordred
  - pip
  - pip:
      - OpenNMT-py==1.2
      - Deprecated
