name: test
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - pandas>=1.1.3
  - seaborn
  - numpy
  - scipy
  - requests
  - rdkit=2020.03.3.0
  - scikit-learn
  - scipy
  - pytorch >=1.7.0,<2.0.0
  - pytest
  - pytest-cov
  - pymatgen>=2020.10.9
  - ruamel.yaml
  - tqdm
  - mordred
  - pip
  - pip:
      - OpenNMT-py==1.2
      - Python-Deprecated
