name: xepy36
channels:
- defaults
- pytorch
dependencies:
- python=3.6
- numpy
- pandas
- tqdm
- seaborn
- requests
- matplotlib
- plotly
- scikit-learn
- scipy
- pytorch
- pytest
- pytest-cov
- pylint
- sphinx
- sphinx_rtd_theme
- jupyter
- pip:
  - pymatgen
  - pymonad
  - ruamel.yaml