name: xepy35
channels:
- defaults
- pytorch
dependencies:
- python=3.5
- numpy
- pandas
- tqdm
- seaborn
- requests
- matplotlib
- plotly
- scikit-learn
- scipy
- pytorch-cpu
- pytest
- pytest-cov
- pip:
  - pymonad
  - pymatgen
  - ruamel.yaml
