name: Deploy PiPy

on:
  push:
    tags:
      - v*

env:
  MPLBACKEN: "Agg"

jobs:
  test_ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: ["ubuntu-18.04"]

    steps:
      - uses: actions/checkout@v2

      - name: Install Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: test
          environment-file: .github/config/linux_win_env.yml
          python-version: ${{ matrix.python-version }}

      - name: Check conda env
        shell: bash -l {0}
        run: .github/workflows/check_env.sh

      - name: Build a binary wheel and a source tarball
        shell: bash -l {0}
        run: |
          python setup.py bdist_wheel

      - name: Publish distribution ðŸ“¦ to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
