name: MacOS

on:
  push:
    branches:
      - master
    paths-ignore:
      - "conda_env/**"
      - "devtools/**"
      - "docs/**"
      - "samples/**"
      - "licenses/**"
      - "hooks/**"
      - ".**"
      - "**.md"
      - "**.txt"
      - "**.in"
      - "**.cfg"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "conda_env/**"
      - "devtools/**"
      - "docs/**"
      - "samples/**"
      - "licenses/**"
      - "hooks/**"
      - ".**"
      - "**.md"
      - "**.txt"
      - "**.in"
      - "**.cfg"

env:
  MPLBACKEN: "Agg"

jobs:
  test_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: ["macos-11.0", "macos-10.15"]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Install Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: test
          environment-file: .github/config/macos_env.yml
          python-version: ${{ matrix.python-version }}

      - name: Check conda env
        shell: bash -l {0}
        run: .github/workflows/check_env.sh

      - name: Install XenonPy
        shell: bash -l {0}
        run: |
          pip install .

      - name: Test XenonPy
        shell: bash -l {0}
        env:
          api_key: ${{ secrets.api_key }}
        run: |
          pytest --cov=./ --cov-report=xml tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        env:
          OS: ${{ matrix.os }}
          PYTHON: ${{ matrix.python-version }}
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: false
